<?php

return [
    ['GET', '/', 'HomeController@index'],
    ['GET', '/register', 'AuthController@showRegister'],
    ['POST', '/register', 'AuthController@register'],
    ['GET', '/login', 'AuthController@showLogin'],
    ['POST', '/login', 'AuthController@login'],
    ['GET', '/logout', 'AuthController@logout', 'auth' => true],
    ['GET', '/profile/edit', 'ProfileController@edit', 'auth' => true],
    ['POST', '/profile/edit', 'ProfileController@update', 'auth' => true],
    ['GET', '/profile/history', 'ProfileController@history', 'auth' => 'member'],
    ['GET', '/cars', 'CarController@index'],
    ['GET', '/cars/{id}', 'CarController@show'],
    ['GET', '/api/cars', 'CarController@apiIndex', 'api' => true],
    ['GET', '/orders/create/{car_id}', 'OrderController@create', 'auth' => 'member'],
    ['POST', '/orders/create/{car_id}', 'OrderController@store', 'auth' => 'member'],
    ['GET', '/orders/{id}/invoice', 'OrderController@invoice', 'auth' => 'member'],
    ['POST', '/orders/{id}/finalize', 'OrderController@finalize', 'auth' => 'member'],
    ['GET', '/orders/{id}/payment', 'OrderController@payment', 'auth' => 'member'],
    ['POST', '/orders/{id}/payment', 'OrderController@processPayment', 'auth' => 'member'],
    ['GET', '/orders/{id}/success', 'OrderController@success', 'auth' => 'member'],
    ['GET', '/blog', 'BlogController@index'],
    ['GET', '/admin/dashboard', 'AdminController@dashboard', 'auth' => 'admin'],
    ['GET', '/admin/members', 'AdminController@members', 'auth' => 'admin'],
    ['GET', '/admin/orders', 'AdminController@orders', 'auth' => 'admin'],
    ['GET', '/admin/cars', 'AdminCarController@index', 'auth' => 'admin'],
    ['GET', '/admin/cars/create', 'AdminCarController@create', 'auth' => 'admin'],
    ['POST', '/admin/cars/create', 'AdminCarController@store', 'auth' => 'admin'],
    ['GET', '/admin/cars/{id}/edit', 'AdminCarController@edit', 'auth' => 'admin'],
    ['POST', '/admin/cars/{id}/edit', 'AdminCarController@update', 'auth' => 'admin'],
    ['POST', '/admin/cars/{id}/delete', 'AdminCarController@destroy', 'auth' => 'admin'],
    ['POST', '/api/orders/cost', 'OrderApiController@calcCost', 'auth' => 'member', 'api' => true],
    ['POST', '/api/orders/{id}/cancel', 'OrderApiController@cancel', 'auth' => 'member', 'api' => true],
    ['POST', '/api/blogs', 'BlogApiController@store', 'auth' => true, 'api' => true],
    ['DELETE', '/api/blogs/{id}', 'BlogApiController@destroy', 'auth' => true, 'api' => true],
    ['DELETE', '/api/members/{id}', 'MemberApiController@destroy', 'auth' => 'admin', 'api' => true],
];
